-- MySQL Script generated by MySQL Workbench
-- 05/25/18 12:19:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cavdb
-- -----------------------------------------------------
-- cavdb
DROP SCHEMA IF EXISTS `cavdb` ;

-- -----------------------------------------------------
-- Schema cavdb
--
-- cavdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cavdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `cavdb` ;

-- -----------------------------------------------------
-- Table `cavdb`.`document_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cavdb`.`document_type` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(10) NULL COMMENT '',
  `description` VARCHAR(25) NULL COMMENT '',
  `state` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cavdb`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cavdb`.`city` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `description` VARCHAR(45) NULL COMMENT '',
  `state` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cavdb`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cavdb`.`profile` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `description` VARCHAR(45) NULL COMMENT '',
  `state` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cavdb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cavdb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `document_type_id` INT NOT NULL COMMENT '',
  `document` INT NOT NULL COMMENT '',
  `name` VARCHAR(20) NOT NULL COMMENT '',
  `lastname` VARCHAR(45) NOT NULL COMMENT '',
  `birthday` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `email` VARCHAR(100) NOT NULL COMMENT '',
  `phone` TINYTEXT NULL COMMENT '',
  `address` VARCHAR(100) NULL COMMENT '',
  `city_id` INT NOT NULL COMMENT '',
  `user` VARCHAR(30) NOT NULL COMMENT '',
  `password` VARCHAR(10) NOT NULL COMMENT '',
  `profile_id` INT NOT NULL COMMENT '',
  `date_sys` DATETIME NULL COMMENT '',
  `state` TINYINT(1) NULL COMMENT '',
  INDEX `fk_user_document_type_idx` (`document_type_id` ASC)  COMMENT '',
  INDEX `fk_user_city1_idx` (`city_id` ASC)  COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_user_profile1_idx` (`profile_id` ASC)  COMMENT '',
  CONSTRAINT `fk_user_document_type`
    FOREIGN KEY (`document_type_id`)
    REFERENCES `cavdb`.`document_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `cavdb`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_profile1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `cavdb`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `cavdb`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cavdb`.`company` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` INT NOT NULL COMMENT '',
  `name` VARCHAR(150) NOT NULL COMMENT '',
  `document_type_id` INT NOT NULL COMMENT '',
  `document` INT NOT NULL COMMENT '',
  `dv` TINYINT(10) NULL COMMENT '',
  `address` VARCHAR(100) NULL COMMENT '',
  `city_id` INT NOT NULL COMMENT '',
  `phone` TINYTEXT NOT NULL COMMENT '',
  `date_sys` DATETIME NULL COMMENT '',
  `state` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_company_city1_idx` (`city_id` ASC)  COMMENT '',
  INDEX `fk_company_document_type1_idx` (`document_type_id` ASC)  COMMENT '',
  INDEX `fk_company_user1_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_company_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `cavdb`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_company_document_type1`
    FOREIGN KEY (`document_type_id`)
    REFERENCES `cavdb`.`document_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_company_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `cavdb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cavdb`.`segmento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cavdb`.`segmento` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `description` VARCHAR(150) NULL COMMENT '',
  `state` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cavdb`.`sede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cavdb`.`sede` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `company_id` INT NOT NULL COMMENT '',
  `name` VARCHAR(150) NULL COMMENT '',
  `phone` TINYTEXT NULL COMMENT '',
  `address` VARCHAR(150) NULL COMMENT '',
  `date_sys` DATETIME NULL COMMENT '',
  `state` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_sede_company1_idx` (`company_id` ASC)  COMMENT '',
  CONSTRAINT `fk_sede_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `cavdb`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cavdb`.`calls`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cavdb`.`calls` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `code` VARCHAR(255) NULL COMMENT '',
  `user_id` INT NOT NULL COMMENT '',
  `date_call` DATETIME NOT NULL COMMENT '',
  `company_id` INT NOT NULL COMMENT '',
  `sede_id` INT NOT NULL COMMENT '',
  `segmento_id` INT NOT NULL COMMENT '',
  `contact_name` VARCHAR(250) NULL COMMENT '',
  `contact_charge` VARCHAR(250) NULL COMMENT '',
  `phone1` TINYTEXT NULL COMMENT '',
  `ext` SMALLINT(3) NULL COMMENT '',
  `cellphone` TINYTEXT NULL COMMENT '',
  `email` VARCHAR(200) NULL COMMENT '',
  `observations` VARCHAR(255) NULL COMMENT '',
  `date_sys_creation` DATETIME NULL COMMENT '',
  `state` TINYINT(1) NULL COMMENT '',
  `date_sys_update` DATETIME NULL COMMENT '',
  `newcall` TINYINT(1) NULL COMMENT '',
  `sendcall` TINYINT(1) NULL COMMENT '',
  `dteage` TINYINT(1) NULL COMMENT '',
  `quoteid` TINYINT(1) NULL COMMENT '',
  `observationsreg` VARCHAR(255) NULL COMMENT '',
  `date_sys_manage` DATETIME NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_calls_company1_idx` (`company_id` ASC)  COMMENT '',
  INDEX `fk_calls_segmento1_idx` (`segmento_id` ASC)  COMMENT '',
  INDEX `fk_calls_user1_idx` (`user_id` ASC)  COMMENT '',
  INDEX `fk_calls_sede1_idx` (`sede_id` ASC)  COMMENT '',
  CONSTRAINT `fk_calls_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `cavdb`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calls_segmento1`
    FOREIGN KEY (`segmento_id`)
    REFERENCES `cavdb`.`segmento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calls_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `cavdb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calls_sede1`
    FOREIGN KEY (`sede_id`)
    REFERENCES `cavdb`.`sede` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
